### ISSUE TITLE
A mistake

### ISSUE THREAD

**Issue by ljy-002** [MapMaths/filedown#1]
![image](https://user-images.githubusercontent.com/63292034/106999090-8eacc080-67c0-11eb-91e2-a8a0f7306487.png)
I encountered an error when trying to execute this command

![image](https://user-images.githubusercontent.com/63292034/106999047-789f0000-67c0-11eb-9143-f2c5c51cb4ae.png)

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/106999270-da5f6a00-67c0-11eb-8add-333f4111ea75.png)
Windows-20H2
Lenovo-ThinkPad

**Comment by ljy-002** [comment]
This should be a problem with my computer

**Comment by MapMaths** [comment]
Seems you type a space between `@`, `mapmaths`, `/` and `filedown`

**Comment by ljy-002** [comment]
I typed
I tried many times

**Comment by MapMaths** [comment]
Well, copy the text here
![image](https://user-images.githubusercontent.com/62785981/107000459-dcc2c380-67c2-11eb-9e0f-f405cd5a5361.png)

**Comment by MapMaths** [comment]
This kinda download problems can be put here, a new feature of GitHub: 
![image](https://user-images.githubusercontent.com/62785981/107000618-21e6f580-67c3-11eb-8fb4-92be9d59c663.png)

**Comment by ljy-002** [comment]
yes

**Comment by ljy-002** [comment]
Okay, that's where the big storage problem is

**Comment by ljy-002** [comment]
![image](https://user-images.githubusercontent.com/63292034/107000847-886c1380-67c3-11eb-849d-da0c046faf32.png)
This is my computer's error

**Comment by MapMaths** [comment]
There's no error, it's just warning. But I have just updated to 1.0.2 which I forgot to upload this morning. So you may update it

**Comment by ljy-002** [comment]
Okay
